name: Storybook Deployment
on:
  workflow_dispatch:

jobs:
  storybook:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9.5
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 22.5.1
          cache: 'pnpm'

      - name: publish to chromatic
        id: chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          buildScriptName: build:storybook
